substitutions:
  devicename: tagreader
  upper_devicename: TagReader

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

  on_boot:
    priority: -10
    then:
    - wait_until:
        api.connected:
    - logger.log: API is connected!
    - if:
        condition:
          switch.is_on: buzzer_enabled
        then:
        - rtttl.play: "success:d=24,o=5,b=100:c,g,b"

switch:
- platform: template
  name: "${upper_devicename} Buzzer Enabled"
  id: buzzer_enabled
  icon: mdi:volume-high
  optimistic: true
- platform: template
  name: "${upper_devicename} LED enabled"
  id: led_enabled
  optimistic: true

#wifi insert your SSID and Your PWD once connected
wifi:
  ap:
    ssid: rfidreader
captive_portal:
# Enable logging
logger:
  baud_rate: 9600
# Enable Home Assistant API
api:
  password: !secret ESP_API_PWD
  services:
  - service: rfidreader_tag_ok
    then:
    - rtttl.play: "beep:d=16,o=5,b=100:b"

  - service: rfidreader_tag_ko
    then:
    - rtttl.play: "beep:d=8,o=5,b=100:b"

ota:
  password: !secret ESP_OTA_PWD
spi:
  clk_pin: TX
  miso_pin: D1
  mosi_pin: D2

pn532:
  cs_pin: D3
  update_interval: 2s
  on_tag:
    then:
    - homeassistant.event:
        event: esphome.tag_scanned
        data:
          tag_id: !lambda 'return x;'
    - if:
        condition:
          switch.is_on: led_enabled
        then:
        - light.turn_on:
            id: activity_led
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
        - delay: 500ms
        - light.turn_off:
            id: activity_led
    - if:
        condition:
          switch.is_on: buzzer_enabled
        then:
        - rtttl.play: "success:d=24,o=5,b=100:c,g,b"
    - if:
        condition:
          switch.is_on: led_enabled
        then:
        - light.turn_on:
            id: activity_led
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
        - delay: 500ms
        - light.turn_off:
            id: activity_led

output:
- platform: esp8266_pwm
  pin: D8
  id: buzzer

rtttl:
  output: buzzer

light:
- platform: fastled_clockless
  chipset: WS2812
  pin: D7
  default_transition_length: 10ms
  num_leds: 1
  rgb_order: GRB
  id: activity_led
  restore_mode: ALWAYS_OFF
  internal: true
